# Generated by Django 5.2.5 on 2025-09-19 09:26

from django.db import migrations




def insert_specialities_info_into_database(apps, schema_editor) :

    Specialities = apps.get_model('HospitalApp', 'Specialities')

    specialities = [
        ["Cardiology", 
        "Cardiology is the branch of medicine that deals with disorders of the heart and circulatory system. It covers a wide range of conditions such as coronary artery disease, heart failure, congenital heart defects, and arrhythmias. Cardiologists perform diagnostic tests like ECGs, echocardiograms, and cardiac catheterizations to assess heart function. They also provide both medical management and interventional treatments, including angioplasty, stent placement, and pacemaker implantation."],

        ["Dermatology", 
        "Dermatology focuses on the diagnosis and treatment of diseases related to the skin, hair, and nails. It covers common conditions like acne, eczema, and psoriasis, as well as complex diseases such as autoimmune skin disorders and skin cancers. Dermatologists also specialize in cosmetic dermatology, offering treatments like chemical peels, laser therapy, and anti-aging procedures. This specialty plays a key role in improving both medical and aesthetic aspects of skin health."],

        ["Orthopedics", 
        "Orthopedics is the medical specialty dedicated to the musculoskeletal system, which includes bones, joints, ligaments, tendons, and muscles. Orthopedic specialists treat fractures, spinal deformities, arthritis, sports injuries, and degenerative conditions. They use both surgical and nonsurgical approaches, ranging from physiotherapy and medication to joint replacements and arthroscopic surgeries. The field also advances in rehabilitation and regenerative treatments to restore mobility and improve quality of life."],

        ["Pediatrics", 
        "Pediatrics is concerned with the overall health and medical care of infants, children, and adolescents. Pediatricians monitor growth and development, provide preventive care through vaccinations, and treat acute and chronic illnesses specific to young age groups. They are trained to address both physical and psychological aspects of child health. Subspecialties like neonatology, pediatric cardiology, and pediatric oncology provide more focused care for complex conditions in children."],

        ["Neurology", 
        "Neurology deals with the study and treatment of disorders affecting the brain, spinal cord, peripheral nerves, and muscles. Neurologists diagnose and manage conditions such as epilepsy, stroke, Parkinson’s disease, multiple sclerosis, and neuropathies. The field relies heavily on advanced diagnostic imaging and neurophysiological tests. Neurology often works hand in hand with neurosurgery, psychiatry, and rehabilitation medicine to provide comprehensive neurological care."],

        ["Gynecology", 
        "Gynecology specializes in the health of the female reproductive system, including the uterus, ovaries, and vagina. Gynecologists treat menstrual disorders, infertility, hormonal imbalances, and gynecological cancers. They provide preventive care such as Pap smears, breast exams, and contraceptive counseling. The field also includes obstetrics, which manages pregnancy, childbirth, and postnatal care, ensuring the overall reproductive and maternal health of women."],

        ["Psychiatry", 
        "Psychiatry is the branch of medicine focused on the diagnosis, treatment, and prevention of mental, emotional, and behavioral disorders. Psychiatrists deal with conditions such as depression, anxiety, bipolar disorder, schizophrenia, and addiction. Treatment often combines psychotherapy, counseling, and medications tailored to individual needs. The specialty is vital in improving mental well-being and quality of life, and includes subspecialties like child psychiatry, forensic psychiatry, and geriatric psychiatry."],

        ["Oncology", 
        "Oncology is the medical field that studies, diagnoses, and treats cancer. It includes medical oncology, radiation oncology, and surgical oncology, offering a multidisciplinary approach to cancer management. Oncologists use chemotherapy, immunotherapy, targeted therapy, and advanced surgical techniques to combat various cancers. Research and innovation in oncology have significantly improved survival rates and quality of life for cancer patients, making it one of the most rapidly advancing fields in medicine."],

        ["Urology", 
        "Urology deals with diseases of the urinary tract and the male reproductive organs. Urologists manage conditions such as kidney stones, urinary tract infections, bladder control problems, and prostate enlargement. They also treat male infertility and cancers of the urinary system. Using minimally invasive surgeries like laparoscopy and endoscopy, urology combines surgical expertise with modern technology to restore normal urinary and reproductive functions."],

        ["ENT", 
        "ENT (Ear, Nose, and Throat), also known as otorhinolaryngology, is a specialty that manages diseases related to the head and neck region. ENT specialists treat ear infections, hearing loss, sinusitis, throat disorders, tonsillitis, and voice problems. They also perform delicate surgeries such as cochlear implants, sinus surgeries, and head & neck tumor removals. This field plays a critical role in maintaining essential functions like breathing, hearing, swallowing, and speech."],

        ["Ophthalmology", 
        "Ophthalmology is the medical and surgical specialty concerned with eye health and vision care. Ophthalmologists diagnose and treat disorders like cataracts, glaucoma, retinal diseases, corneal problems, and refractive errors. They perform advanced procedures such as LASIK, retinal surgery, and corneal transplants. By combining preventive care, medical management, and microsurgery, ophthalmology ensures the preservation of sight and the prevention of blindness."],

        ["Nephrology", 
        "Nephrology focuses on the study and treatment of kidney-related diseases. Nephrologists manage chronic kidney disease, glomerulonephritis, electrolyte imbalances, and hypertension related to kidney dysfunction. They play a central role in dialysis treatment, kidney transplants, and critical care nephrology. This field emphasizes both life-saving interventions and preventive strategies to slow disease progression and improve patient outcomes."],

        ["Endocrinology", 
        "Endocrinology is the branch of medicine dealing with hormonal imbalances and disorders of endocrine glands. Endocrinologists treat diabetes, thyroid diseases, adrenal disorders, pituitary problems, and reproductive hormonal issues. They specialize in regulating metabolism, growth, and development, which are controlled by hormones. Advances in endocrinology have greatly improved the management of chronic diseases like diabetes and obesity, making it crucial for long-term health."],

        ["Gastroenterology", 
        "Gastroenterology focuses on the digestive system, including the esophagus, stomach, intestines, liver, pancreas, and gallbladder. Gastroenterologists diagnose and treat conditions like acid reflux, ulcers, hepatitis, inflammatory bowel disease, and liver cirrhosis. They use endoscopic techniques to visualize and treat gastrointestinal issues without invasive surgery. This specialty plays a vital role in nutrition, metabolism, and prevention of digestive cancers."],

        ["Pulmonology", 
        "Pulmonology is the specialty that deals with diseases of the respiratory system, including the lungs and airways. Pulmonologists manage asthma, chronic obstructive pulmonary disease (COPD), tuberculosis, sleep apnea, and lung infections. They use diagnostic tools such as pulmonary function tests, bronchoscopy, and imaging to evaluate respiratory health. Pulmonology is essential in both acute care, like critical care ventilation, and long-term management of chronic lung diseases."],
    ]


    for speciality, description in specialities :

        speciality_obj = Specialities(
            speciality = speciality,
            description = description,
        )

        speciality_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_inserted_models_into_database'),
    ]

    operations = [
        migrations.RunPython(insert_specialities_info_into_database),
    ]
