# Generated by Django 5.2.5 on 2025-09-19 09:27

from django.db import migrations


def insert_doctors_info_into_database(apps, schema_editor) :

    Doctor = apps.get_model('HospitalApp', 'Doctors')

    doctors_data = [
    ["Dr. Arjun Mehta", "arjunm", "pass123", "Cardiology", "MBBS | MD (Cardiology) | DM (Cardiology)", 12, 1800],
    ["Dr. Priya Sharma", "priyas", "pass123", "Dermatology", "MBBS | MD (Dermatology) | Fellowship in Cosmetic Dermatology | Diploma in Aesthetic Medicine", 10, 1500],
    ["Dr. Rajesh Kapoor", "rajeshk", "pass123", "Orthopedics", "MBBS | MS (Orthopedics) | M.Ch (Orthopedic Surgery)", 15, 2200],
    ["Dr. Neha Gupta", "nehag", "pass123", "Pediatrics", "MBBS | MD (Pediatrics) | DNB (Pediatrics) | Fellowship in Neonatology", 11, 2000],
    ["Dr. Vivek Rao", "vivekr", "pass123", "Neurology", "MBBS | MD (General Medicine) | DM (Neurology) | Fellowship in Stroke Medicine", 18, 2500],
    ["Dr. Ananya Singh", "ananyas", "pass123", "Gynecology", "MBBS | MD (Gynecology) | Fellowship in Reproductive Medicine | DGO", 9, 1900],
    ["Dr. Karan Verma", "karanv", "pass123", "Psychiatry", "MBBS | MD (Psychiatry) | DNB (Psychiatry) | Fellowship in Child Psychiatry", 13, 1700],
    ["Dr. Sneha Iyer", "snehai", "pass123", "Oncology", "MBBS | MD (Oncology) | Fellowship in Surgical Oncology | PhD (Cancer Biology)", 14, 2400],
    ["Dr. Rahul Nair", "rahuln", "pass123", "Urology", "MBBS | MS (Urology) | M.Ch (Urology) | Fellowship in Endourology", 12, 2100],
    ["Dr. Swati Deshmukh", "swatid", "pass123", "ENT", "MBBS | MS (ENT) | DNB (Otorhinolaryngology) | Fellowship in Head & Neck Surgery", 8, 1600],
    ["Dr. Varun Kumar", "varunk", "pass123", "Ophthalmology", "MBBS | MS (Ophthalmology) | Fellowship in Retina Surgery | DNB (Ophthalmology)", 10, 1500],
    ["Dr. Meera Menon", "meeram", "pass123", "Nephrology", "MBBS | MD (Nephrology) | DM (Nephrology) | Fellowship in Renal Transplantation", 16, 2300],
    ["Dr. Suresh Reddy", "sureshr", "pass123", "Endocrinology", "MBBS | MD (Endocrinology) | DM (Endocrinology) | Fellowship in Diabetes & Metabolism", 15, 2000],
    ["Dr. Aditi Jain", "aditij", "pass123", "Gastroenterology", "MBBS | MD (Medicine) | DM (Gastroenterology) | Fellowship in Hepatology", 17, 2500],
    ["Dr. Mahesh Vardhan", "maheshv", "pass123", "Pulmonology", "MBBS | MD (Pulmonology) | DNB (Respiratory Medicine) | Fellowship in Critical Care Medicine", 12, 1800],
]


    for doctor_name, username, password, specialization, degree,experience, consultation_fee in doctors_data :

        Doctor.objects.create(

            doctor_name = doctor_name,
            username = username,
            password = password,
            specialization = specialization,
            degree = degree, 
            experience = experience, 
            consultation_fee = consultation_fee,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_insert_specialities_info_into_database'),
    ]

    operations = [
        migrations.RunPython(insert_doctors_info_into_database),
    ]
