# Generated by Django 5.2.5 on 2025-09-19 09:27

from django.db import migrations



def insert_diagnosis_main_tests_into_database(apps, schema_editor):
    DiagnosisTests = apps.get_model('HospitalApp', 'DiagnosisTests')

    tests_with_descriptions = [
        (
            'Pathology / BioChemistry(Blood)',
            'Includes complete blood count (CBC), liver function tests (LFT), kidney function tests (KFT), lipid profile, blood sugar, electrolytes, and other biochemical markers to evaluate overall organ health.'
        ),
        (
            'Radiology / Imaging',
            'Includes X-ray (bones, lungs), ultrasound (abdomen, pelvis), CT scan, MRI, PET scan, and mammography to visualize organs such as brain, heart, lungs, liver, kidneys, joints, and detect abnormalities.'
        ),
        (
            'Cardiology / Heart Tests',
            'Includes ECG (electrocardiogram), echocardiography, treadmill stress test, Holter monitoring, cardiac enzymes, angiography, and other investigations to check heart rhythm, blood flow, and cardiac function.'
        ),
        (
            'Pulmonology / Lung Tests',
            'Includes spirometry (lung function test), chest X-ray, CT thorax, arterial blood gas analysis, bronchoscopy, and diffusion capacity tests for evaluating asthma, COPD, infections, and other respiratory conditions.'
        ),
        (
            'MicroBiology / Infectious Diseases',
            'Includes blood culture, urine culture, sputum culture, stool culture, throat swab, malaria test, tuberculosis tests, HIV, hepatitis panel, and other microbiological tests to identify bacteria, viruses, fungi, or parasites.'
        ),
        (
            'Immunology / Hormonal Tests',
            'Includes thyroid function tests (T3, T4, TSH), reproductive hormones (FSH, LH, estrogen, progesterone, testosterone), cortisol, insulin, vitamin D, autoimmune markers (ANA, RF), and allergy panels.'
        ),
        (
            'Cancer Screening / Special Tests',
            'Includes tumor markers (PSA for prostate, CA-125 for ovarian, CEA for colon, AFP for liver, BRCA gene testing), Pap smear, mammography, colonoscopy, and specialized molecular/genetic screening for cancers.'
        ),
        (
            'General / Preventive Health Check ups',
            'Includes routine health check packages covering blood pressure, BMI, blood tests, urine analysis, ECG, chest X-ray, ultrasound, eye exam, dental check, vaccinations, and lifestyle-related risk assessments.'
        ),
    ]

    for testname, description in tests_with_descriptions:
        diagnosis_test = DiagnosisTests(
            testname=testname,
            test_description=description
        )
        diagnosis_test.save()


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_insert_doctors_info_into_database'),
    ]

    operations = [
        migrations.RunPython(insert_diagnosis_main_tests_into_database),
    ]
